# List of worlds where portals can be built
WorldsCanBuildPortals:
  - world
  
# Max number of portals per world, 0 ignores check
MaxPortalsPerWorld: 3

# Max number of portals that can be created by a simgle player, 0 ignores check
MaxPortalsPerPlayer: 1

# Minimum distance allowed between portals, 0 ignores check
MinDistanceBetweenPortals: 300

# Maximum distance a player can be from a portal for an Eye of Ender to be able
# to locate it, 0 ignores check
MaxPortalSearchDistance: 1000

# If enabled, on portal creation, if there is one unique group reinforcement on
# the portal frame, the portal will only be usable by members of said group
EnableNameLayerGroupChecking: false

CustomPortalBlock:
  Name: Portal Block
  Type: OBSIDIAN
  Lore:
    - Used to create End Portals
  Glow: true
  Recipe: ShapedRecipe
  ShapedRecipe:
    Shape:
      - OEO
      - EBE
      - OEO
    Ingredients:
      OBSIDIAN: O
      EYE_OF_ENDER: E
      BLAZE_ROD: B
  ShapelessRecipe:
    Ingredients:
      OBSIDIAN: 4
      EYE_OF_ENDER: 4
      BLAZE_ROD: 1